### ISSUE TITLE
请问TPE算法优化的超参数必须是分类特征（categorical features）么

### ISSUE THREAD

**Issue by ExileForSky** [huaweicloudDocs/modelarts#1]
请问TPE算法优化的超参数必须是分类特征（categorical features）么，我在一篇论文综述中看到TPE describes the configura-
tion space by a generative process and supports categorical features.想确认一下TPE对于优化的超参数类型有限制么

**Comment by WJ-Lai** [comment]
您好，感谢您的反馈。您提交的内容已交由华为云工程师进行分析和评估，评估完成后会及时将结果反馈给您，请您留意Github消息。谢谢！

**Comment by WJ-Lai** [comment]
TPE算法是没有限制的，但出于面对普通用户节省资源的目的，ModelArts在前端限制了TPE的超参数必须是float，如果想离散型和连续型参数混用的话，可以调用rest接口。

**Comment by WJ-Lai** [comment]
您反馈的疑问在华为云帮助中心已发布，详见：https://support.huaweicloud.com/modelarts_faq/modelarts_05_0378.html
感谢并期待您的再次反馈。
